# Site settings
title: Son of a Gun Seasoning
email: info@thespicehut.com
url: https://son-of-a-gun.github.io
description: "Located in the rainy Pacific Northwest, we have worked hard to prove that even us Washingtonians can produce a damn good bbq. Our company, The Spice Hut, has been producing custom and original blends and spices for nearly 15 years, and this has been an important process for us to establish Son of a Gun, a fun and whimsical take on wild west grilling, and loaded with more flavor than you could imagine."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#e2dbe3'
  links: '#e1c192'

# Footer settings
footer: Son of a Gun Seasoning

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
