# Site settings
title: Son of a Gun Seasoning
email: info@thespicehut.com
url: https://son-of-a-gun.github.io
description: "Damn Good Spices."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#e2dbe3'
  links: '#dba75c'

# Footer settings
footer: Son of a Gun Seasoning

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
